### ISSUE TITLE
Startup fails when metrics servlet is enabled but no environment is set

### ISSUE THREAD

**Issue by gpor89** [kumuluz/kumuluzee-metrics#1]
Start service without kumuluzee.env.name configuration key set and
kumuluzee.metrics.servlet.enabled set to true.

Exception
Caused by: java.lang.NullPointerException
	at com.kumuluz.ee.metrics.MetricsInitiator.initialiseBean(MetricsInitiator.java:85)

is thrown. As a result metrics should be enabled in this case.

**Comment by urbim** [comment]
Should be fixed in 1.1.2.
