### ISSUE TITLE
Metrics throws exception on concurrency

### ISSUE THREAD

**Issue by gpor89** [kumuluz/kumuluzee-metrics#3]
KumuluzEE metrics implementation does not update metrics as it should when its used concurrently. 

When metric is registered with Metadata reusable property to false (by default) it fails with runtime exception "A metric named ... already exists" which is serious issue since metrics api should not fail (at least not with runtime exceptions like this). Microprofile describes counters api as 

> /**
     * Return the {@link Counter} registered under the {@link Metadata}'s name; or create and register 
     * a new {@link Counter} if none is registered.
     * If a {@link Counter} was created, the provided {@link Metadata} object will be registered.
     * <p>
     * Note: The {@link Metadata} will not be updated if the metric is already registered.
     * </p>
     * 
     * @param metadata the name of the metric
     * @return a new or pre-existing {@link Counter}
     */
    public abstract Counter counter(Metadata metadata);

According to documentation, this API should return new counter or pre-existing one. I'm not sure if this is bug in kumuluzEE or Dropwizzards but it should be fixed somewhere.

Second issue appears when reusable property is set to true, counter API does not fail with exception, but it does not update metrics as it should. To demonstrate this issue i have created two concurrency tests available here: https://github.com/gpor89/kumuluzee-metrics/commit/bd408af9023fcf9e028d5a0a0a84a013ae59e941

**Comment by urbim** [comment]
Hi!

This was fixed in the latest commit, please reopen if you notice any more issues.

**Comment by gpor89** [comment]
I will check your solution. Thanks for fixing this issue.
